apiVersion: batch/v1
kind: Job
metadata:
  name: debezium-register
  labels:
    app: debezium-register
spec:
  template:
    metadata:
      labels:
        app: debezium-register
    spec:
      restartPolicy: OnFailure
      containers:
        - name: register
          image: curlimages/curl:8.5.0
          command:
            - /bin/sh
            - -lc
            - >
              sleep 15 &&
              curl -s -X POST -H "Content-Type: application/json" --data @/config/connector.json http://kafka-connect:8083/connectors ||
              curl -s -X PUT -H "Content-Type: application/json" --data @/config/connector.json http://kafka-connect:8083/connectors/inventory-postgres-connector/config
          volumeMounts:
            - name: cfg
              mountPath: /config
      volumes:
        - name: cfg
          configMap:
            name: debezium-connector
            items:
              - key: connector.json
                path: connector.json
