apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: marketplace

resources:
  - namespace.yaml
  - postgres-statefulset.yaml
  - postgres-service.yaml
  - redis-deployment.yaml
  - redis-service.yaml
  - opensearch-statefulset.yaml
  - opensearch-service.yaml
  - kafka-statefulset.yaml
  - kafka-service.yaml
  - kafka-connect-deployment.yaml
  - kafka-connect-service.yaml
  - minio-bucket-job.yaml
  - topics-job.yaml
  - debezium-connector-configmap.yaml
  - debezium-register-job.yaml
  - s3-sink-configmap.yaml
  - s3-sink-register-job.yaml
  - api-gateway-deployment.yaml
  - api-gateway-service.yaml
  - identity-deployment.yaml
  - identity-service.yaml
  - seller-deployment.yaml
  - seller-service.yaml
  - catalog-deployment.yaml
  - catalog-service.yaml
  - search-deployment.yaml
  - search-service.yaml
  - pricing-deployment.yaml
  - pricing-service.yaml
  - inventory-deployment.yaml
  - inventory-service.yaml
  - cart-deployment.yaml
  - cart-service.yaml
  - checkout-deployment.yaml
  - checkout-service.yaml
  - payments-deployment.yaml
  - payments-service.yaml
  - orders-deployment.yaml
  - orders-service.yaml
  - fulfillment-deployment.yaml
  - fulfillment-service.yaml
  - notifications-deployment.yaml
  - notifications-service.yaml
  - reviews-deployment.yaml
  - reviews-service.yaml
  - analytics-deployment.yaml
  - analytics-service.yaml
  - transformer-api-deployment.yaml
  - transformer-api-service.yaml
  - minio-deployment.yaml
  - minio-service.yaml
