apiVersion: v1
kind: ConfigMap
metadata:
  name: s3-sink-connector
data:
  connector.json: |
    {
      "name": "s3-sink",
      "config": {
        "connector.class": "io.aiven.kafka.connect.s3.S3SinkConnector",
        "tasks.max": "2",
        "topics": "inventory.cdc,orders.events,payments.events",
        "aws.access.key.id": "${env:AWS_ACCESS_KEY_ID}",
        "aws.secret.access.key": "${env:AWS_SECRET_ACCESS_KEY}",
        "aws.s3.endpoint": "http://minio:9000",
        "aws.s3.path.style.access": "true",
        "s3.bucket.name": "events",
        "file.compression.type": "gz",
        "format.output.type": "jsonl",
        "value.converter": "org.apache.kafka.connect.json.JsonConverter",
        "value.converter.schemas.enable": "false",
        "key.converter": "org.apache.kafka.connect.storage.StringConverter",
        "part.size": "5242880",
        "topics.dir": "cdc",
        "name": "s3-sink"
      }
    }
