apiVersion: v1
kind: Service
metadata:
  name: seller
  labels:
    app: seller
spec:
  selector:
    app: seller
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  type: ClusterIP
