apiVersion: v1
kind: Service
metadata:
  name: transformer-api
  labels:
    app: transformer-api
spec:
  selector:
    app: transformer-api
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  type: ClusterIP
